### ISSUE TITLE
'Dashboard' button leads to 'Console'

### ISSUE THREAD

**Issue by usrme** [shuttle-hq/www#107]
The top menu has a button 'Dashboard' that leads to a site called Shuttle Console, so perhaps the button text and its internal representation be renamed to 'Console'?

![image](https://github.com/shuttle-hq/www/assets/5902545/09c29b89-7bb3-469e-ac35-fd0ab0cd3dc0)

**Comment by GugaGongadze** [comment]
Thanks, @usrme for reporting this!
