### ISSUE TITLE
Shuttle Console has boilerplate text for Resources

### ISSUE THREAD

**Issue by usrme** [shuttle-hq/www#108]
When looking at the Resources section of a project, it seems as if boilerplate text was left in by accident:

![image](https://github.com/shuttle-hq/www/assets/5902545/c47dacef-c091-4170-9739-429d3a87b1b2)

Namely, the "Short one sentence explanation of what is a resource." bit. It would probably be easier to just link to the [Resources overview documentation page](https://docs.shuttle.rs/resources/overview) or just forego that line entirely as if one clicks on the "How to add a resource" button, then there is a link to the Resources documentation anyway, **but it doesn't lead directly to the Resources section**.

I would have gone ahead and submitted a PR for this, but I couldn't find the source code for the Console pages :thinking:

**Comment by GugaGongadze** [comment]
Thanks, @usrme!

Console code-base is yet to be open-sourced, fixed and deployed it.
