### ISSUE TITLE
Refreshing page on /dashboard loads up the main page instead

### ISSUE THREAD

**Issue by gingerdeer** [shuttle-hq/www#45]
After logging in to the /dashboard page, if you press refresh you are directed back to the main shuttle.rs page.

Expected behaviour would be to reload the same page you were on when refreshing.

**Comment by gingerdeer** [comment]
Looking at the code, looks like this is what's happening https://community.auth0.com/t/next-js-lose-useuser-data-after-refresh-a-page-which-contains-data-of-user/90324

**Comment by GugaGongadze** [comment]
Hi, @gingerdeer, thanks for reporting this. Turns out it was just a case of not checking whether user information had loaded or not.
