### ISSUE TITLE
Copying example code breaks on :: in use statements

### ISSUE THREAD

**Issue by marcusradell** [shuttle-hq/www#87]
Given a new file `www/_launchpad/test.mdx`
And the content
````
```rust
use axum::Router;
```
````
When I use the copy button in the rendered HTML
Then I actually get
```rust
use axum[object Object]Router;
```

I expected
```rust
use axum::Router;
```

It might not be very simple to fix, and it's only an issue for use statements as far as I've seen. So feel free to close this as a wontfix and focus on more important stuff. Now you know :-)

**Comment by ivancernja** [comment]
Thanks @marcusradell for reporting this, and sorry for the delay!

@GugaGongadze could you look into this?

**Comment by GugaGongadze** [comment]
Hi @marcusradell, this should be fixed now, thanks!
